modLoader = "javafml" #mandatory
loaderVersion = "[36,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license = "GPLv3"
[[mods]] #mandatory
modId = "weatherforecast" #mandatory
version = "1.0.0" #mandatory
displayName = "WeatherForecast" #mandatory
authors = "YueSha" #optional
description = '''
Forecast future weather
'''
[[dependencies.weatherforecast]] #optional
modId = "forge" #mandatory
mandatory = true #mandatory
versionRange = "[36,)" #mandatory
ordering = "NONE"
side = "BOTH"
[[dependencies.weatherforecast]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16.5,1.17)"
ordering = "NONE"
side = "BOTH"
