modLoader = "javafml" #mandatory
loaderVersion = "[36,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license = "GPLv3"
issueTrackerURL="https://github.com/TeamMoegMC/Weather-Forecast/issues"
[[mods]] #mandatory
modId = "weatherforecast" #mandatory
version = "1.0.3" #mandatory
displayName = "Weather Forecast" #mandatory
logoFile="logo.png" #optional
authors = "YueSha" #optional
credits="Many thanks to Luyuuke and duck_egg for creating textures" #optional
description = '''
Forecast future weather & Show ambient temperature
'''
[[dependencies.weatherforecast]] #optional
modId = "forge" #mandatory
mandatory = true #mandatory
versionRange = "[36,)" #mandatory
ordering = "NONE"
side = "BOTH"
[[dependencies.weatherforecast]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16.5,1.17)"
ordering = "NONE"
side = "BOTH"
